import { useEffect, useRef, useState } from 'react';
import { supabase } from './supabase';

const labels = {gestor:'Gestor',trainer:'Treinador',aluno:'Aluno',ativa:'Ativa',pausada:'Pausada',cancelada:'Cancelada',expirada:'Expirada',pago:'Pago',pendente:'Pendente',falhado:'Falhado',reembolsado:'Reembolsado',dinheiro:'Dinheiro',transferencia:'Transferência',outro:'Outro'};
const money = (n, currency='AOA') => new Intl.NumberFormat('pt-AO',{style:'currency',currency}).format(Number(n||0));
const date = v => v ? new Date(v.length===10 ? v+'T12:00:00' : v).toLocaleDateString('pt-AO') : '—';
const today = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const initial = n => n?.split(' ').filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase() || 'FC';
const text = v => labels[v] || String(v ?? '—').replaceAll('_',' ');
const paths = {
 overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',
 members:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M16 3a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
 finance:'M3 5h18v14H3z M3 9h18 M15 14h3',
 training:'M3 8v8 M6 5v14 M18 5v14 M21 8v8 M6 12h12',
 progress:'M4 19V5 M4 19h17 M7 14l4-4 4 2 5-7',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',
 plus:'M12 5v14 M5 12h14', search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0', arrow:'M5 12h14 M14 7l5 5-5 5', exit:'M9 4H4v16h5 M10 12h11 M17 8l4 4-4 4',refresh:'M20 7v5h-5 M4 17v-5h5 M6 6a8 8 0 0 1 14 6 M18 18A8 8 0 0 1 4 12',check:'M5 12l4 4L19 6',close:'M6 6l12 12 M6 18L18 6'
};
function Icon({name,size=20}) {return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.overview}/></svg>;}
function Badge({value}) {return <span className={`badge ${value===true||['pago','ativa','gestor'].includes(value)?'green':value===false||['falhado','cancelada','expirada'].includes(value)?'muted':'amber'}`}><i/>{typeof value==='boolean'?(value?'Ativo':'Inativo'):text(value)}</span>;}
function Empty({title='Ainda não existem registos',detail='Os novos registos aparecerão aqui.',action}) {return <div className="empty"><span className="empty-icon"><Icon name="overview" size={27}/></span><h3>{title}</h3><p>{detail}</p>{action}</div>;}
function Metric({label,value,detail,icon}) {return <article className="metric"><div className="metric-top"><span>{label}</span><Icon name={icon}/></div><strong>{value}</strong><small>{detail}</small></article>;}

async function all(table,gymId) {
  const rows=[];
  for(let offset=0;;offset+=1000) {
    const {data,error}=await supabase.from(table).select('*').eq('ginasio_id',gymId).range(offset,offset+999).order(table==='membros_ginasio'?'utilizador_id':'id');
    if(error) throw error;
    rows.push(...data);
    if(data.length<1000) return rows;
  }
}

export default function Dashboard({gym,gyms,membership,user,onSelectGym,onSaved,onLogout,authError}) {
  const role=membership?.funcao,manager=role==='gestor',staff=manager||role==='trainer';
  const [page,setPage]=useState('overview');
  const [tab,setTab]=useState('');
  const [query,setQuery]=useState('');
  const [data,setData]=useState({});
  const [loading,setLoading]=useState(true);
  const [errors,setErrors]=useState([]);
  const [notice,setNotice]=useState('');
  const [modal,setModal]=useState(null);
  const version=useRef(0),alive=useRef(true);
  const tables=['membros_ginasio','exercicios','planos_treino','treinos','treino_exercicios','registos_treino','registos_series','medicoes',...(role!=='trainer'?['planos_mensalidade','subscricoes','pagamentos']:[])];
  async function load() {
    const rev=++version.current;
    setLoading(true);setErrors([]);
    const results=await Promise.allSettled(tables.map(t=>all(t,gym.id)));
    if(!alive.current||version.current!==rev)return;
    const next={},failures=[];
    results.forEach((r,i)=>{next[tables[i]]=r.status==='fulfilled'?r.value:[];if(r.status==='rejected')failures.push(tables[i]);});
    setData(next);setErrors(failures);setLoading(false);
  }
  useEffect(()=>{alive.current=true;load();return()=>{alive.current=false;version.current++;};},[gym.id,role]);
  const rows=t=>data[t]||[];
  const members=rows('membros_ginasio');
  const alumnos=members.filter(m=>m.funcao==='aluno'&&m.ativo);
  const memberName=id=>members.find(m=>m.utilizador_id===id)?.nome||'Membro';
  const planName=id=>rows('planos_treino').find(x=>x.id===id)?.nome||'Plano';
  const treinoName=id=>rows('treinos').find(x=>x.id===id)?.nome||'Treino livre';
  const exerciseName=id=>rows('exercicios').find(x=>x.id===id)?.nome||'Exercício';
  const month=today().slice(0,7);
  const payments=rows('pagamentos');
  const paid=payments.filter(p=>p.estado==='pago'&&p.pago_em?.startsWith(month));
  const financeTotal=(list)=>{const currencies=[...new Set(list.map(p=>p.moeda))];return currencies.length>1?`${list.length} pagamentos` : money(list.reduce((s,p)=>s+Number(p.valor),0),currencies[0]||'AOA');};
  const myRecords=rows('registos_treino').filter(r=>r.aluno_id===user.id);
  const activeSubs=rows('subscricoes').filter(s=>s.estado==='ativa'&&s.inicio<=today()&&s.fim>=today());
  const menu=[['overview','Visão geral'],['members',staff?'Membros':'O meu vínculo'],...(role!=='trainer'?[['finance',manager?'Financeiro':'Mensalidade']]:[]),['training','Treinos'],['progress','Progresso'],['settings','Definições']];
  const headings={overview:['O seu ginásio, em perspetiva.','Tudo o que importa, num só lugar.'],members:['Pessoas que fazem parte.','Acompanhe os membros e a equipa do seu ginásio.'],finance:['Uma gestão financeira clara.','Planos, subscrições e pagamentos organizados.'],training:['Treinar com propósito.','Uma biblioteca de exercícios e planos para cada objetivo.'],progress:['Cada evolução conta.','Registe treinos e acompanhe as medições ao longo do tempo.'],settings:['A identidade do seu ginásio.','Personalize o nome e o logótipo apresentados aos seus membros.']};
  function navigate(p){setPage(p);setTab('');setQuery('');setNotice('');}
  const opts=(list,value,label)=>list.map(x=>({value:x[value],label:typeof label==='function'?label(x):x[label]}));
  const field=(key,label,type='text',extra={})=>({key,label,type,...extra});
  const student=()=>field('aluno_id','Aluno','select',{required:true,options:opts(alumnos,'utilizador_id','nome'),fixed:staff?undefined:user.id});
  const config={
    exercicios:{title:'Novo exercício',fields:[field('nome','Nome','text',{required:true,maxLength:120}),field('grupo_muscular','Grupo muscular','select',{options:['peito','costas','ombros','biceps','triceps','antebraco','abdominais','quadriceps','posteriores','gluteos','gemeos','corpo_inteiro','cardio','mobilidade'].map(v=>({value:v,label:text(v)}))}),field('equipamento','Equipamento','text',{maxLength:80}),field('descricao','Descrição','textarea',{maxLength:2000}),field('video_url','Vídeo (endereço HTTPS)','url',{pattern:'https://.*',maxLength:500})]},
    planos_treino:{title:'Novo plano de treino',fields:[student(),field('nome','Nome do plano','text',{required:true,maxLength:120}),field('objetivo','Objetivo','select',{options:['hipertrofia','forca','emagrecimento','resistencia','saude','reabilitacao','outro'].map(v=>({value:v,label:text(v)}))}),field('data_inicio','Início','date',{required:true,default:today()}),field('data_fim','Fim','date'),field('notas','Notas','textarea',{maxLength:2000})]},
    treinos:{title:'Novo treino',fields:[field('plano_id','Plano de treino','select',{required:true,options:opts(rows('planos_treino'),'id',x=>`${x.nome} · ${memberName(x.aluno_id)}`)}),field('nome','Nome do treino','text',{required:true,maxLength:60}),field('ordem','Ordem','number',{required:true,default:1,min:1,max:50,step:1})]},
    treino_exercicios:{title:'Adicionar exercício ao treino',fields:[field('treino_id','Treino','select',{required:true,options:opts(rows('treinos'),'id',x=>`${x.nome} · ${planName(x.plano_id)}`)}),field('exercicio_id','Exercício','select',{required:true,options:opts(rows('exercicios').filter(x=>x.ativo),'id','nome')}),field('ordem','Ordem','number',{required:true,default:1,min:1,max:100,step:1}),field('series','Séries','number',{required:true,default:3,min:1,max:20,step:1}),field('repeticoes','Repetições','text',{required:true,default:'10',pattern:'[0-9]{1,3}(-[0-9]{1,3})?|ate falhar|[0-9]{1,4}s',hint:'Ex.: 10, 8-12, 60s ou ate falhar.'}),field('carga_kg','Carga (kg)','number',{min:0,max:9999.99,step:0.01}),field('descanso_seg','Descanso (segundos)','number',{min:0,max:1800,step:1}),field('notas','Notas','textarea',{maxLength:500})]},
    planos_mensalidade:{title:'Novo plano de mensalidade',fields:[field('nome','Nome','text',{required:true,maxLength:80}),field('preco','Preço','number',{required:true,min:0,max:9999999999.99,step:0.01}),field('moeda','Moeda','select',{required:true,default:'AOA',options:['AOA','EUR','USD'].map(v=>({value:v,label:v}))}),field('duracao_dias','Duração (dias)','number',{required:true,default:30,min:1,max:730,step:1}),field('descricao','Descrição','textarea',{maxLength:500})]},
    subscricoes:{title:'Nova subscrição',fields:[student(),field('plano_id','Plano de mensalidade','select',{required:true,options:opts(rows('planos_mensalidade').filter(p=>p.ativo),'id',p=>`${p.nome} · ${money(p.preco,p.moeda)}`)}),field('inicio','Início','date',{required:true,default:today()}),field('fim','Fim','date',{required:true}),field('estado','Estado','select',{required:true,default:'ativa',options:['ativa','pausada','cancelada','expirada'].map(v=>({value:v,label:text(v)}))})]},
    pagamentos:{title:'Registar pagamento manual',fields:[student(),field('subscricao_id','Subscrição (opcional)','select',{options:opts(rows('subscricoes'),'id',s=>`${memberName(s.aluno_id)} · até ${date(s.fim)}`),depends:'aluno_id',filter:(s,v)=>s.aluno_id===v,source:rows('subscricoes')}),field('valor','Valor recebido','number',{required:true,min:0.01,max:9999999999.99,step:0.01}),field('moeda','Moeda','select',{required:true,default:'AOA',options:['AOA','EUR','USD'].map(v=>({value:v,label:v}))}),field('metodo','Método','select',{required:true,default:'dinheiro',options:['dinheiro','transferencia','outro'].map(v=>({value:v,label:text(v)}))}),field('estado','Estado','select',{required:true,default:'pago',options:['pago','pendente','falhado'].map(v=>({value:v,label:text(v)}))}),field('referencia','Referência','text',{maxLength:120})]},
    registos_treino:{title:'Registar treino realizado',fields:[student(),field('treino_id','Treino (opcional)','select',{options:opts(rows('treinos'),'id',x=>`${x.nome} · ${planName(x.plano_id)}`),depends:'aluno_id',filter:(t,v)=>rows('planos_treino').find(p=>p.id===t.plano_id)?.aluno_id===v,source:rows('treinos')}),field('realizado_em','Data e hora','datetime-local',{required:true,default:today()+'T'+new Date().toTimeString().slice(0,5)}),field('duracao_min','Duração (minutos)','number',{min:1,max:600,step:1}),field('esforco','Esforço (1–10)','number',{min:1,max:10,step:1}),field('notas','Notas','textarea',{maxLength:1000})]},
    registos_series:{title:'Registar série realizada',fields:[field('registo_id','Treino realizado','select',{required:true,options:opts(rows('registos_treino'),'id',r=>`${memberName(r.aluno_id)} · ${date(r.realizado_em)} · ${treinoName(r.treino_id)}`)}),field('exercicio_id','Exercício','select',{required:true,options:opts(rows('exercicios'),'id','nome')}),field('serie','Número da série','number',{required:true,default:1,min:1,max:50,step:1}),field('repeticoes','Repetições','number',{min:0,max:1000,step:1}),field('carga_kg','Carga (kg)','number',{min:0,max:9999.99,step:0.01})]},
    medicoes:{title:'Nova medição',fields:[student(),field('medido_em','Data','date',{required:true,default:today()}),...['peso_kg','altura_cm','gordura_pct','cintura_cm','anca_cm','peito_cm','braco_cm','coxa_cm'].map((k,i)=>field(k,['Peso (kg)','Altura (cm)','Gordura (%)','Cintura (cm)','Anca (cm)','Peito (cm)','Braço (cm)','Coxa (cm)'][i],'number',{step:k==='peso_kg'?0.01:0.1,min:[20,80,2,30,30,30,10,20][i],max:[400,250,70,250,250,250,80,120][i]})),field('notas','Notas','textarea',{maxLength:1000})]}
  };
  function create(table,defaults={}){setModal({table,...config[table],defaults});}
  function edit(table,row){const allowed={exercicios:['nome','grupo_muscular','equipamento','descricao','video_url'],planos_treino:['nome','objetivo','data_inicio','data_fim','notas'],treinos:['nome','ordem'],treino_exercicios:['ordem','series','repeticoes','carga_kg','descanso_seg','notas'],planos_mensalidade:['nome','preco','moeda','duracao_dias','descricao'],registos_treino:['duracao_min','esforco','notas'],registos_series:['serie','repeticoes','carga_kg'],medicoes:['medido_em','peso_kg','altura_cm','gordura_pct','cintura_cm','anca_cm','peito_cm','braco_cm','coxa_cm','notas'],subscricoes:['fim','estado'],pagamentos:['valor','moeda','metodo','estado','referencia']};setModal({table,title:'Editar registo',fields:config[table].fields.filter(f=>allowed[table]?.includes(f.key)),defaults:row,id:row.id});}
  async function toggle(table,row){setNotice('');try{const {data:updated,error}=await supabase.from(table).update({ativo:!row.ativo}).eq('id',row.id).eq('ginasio_id',gym.id).select('id');if(error||!updated?.length)throw error||Error();setNotice('Estado atualizado.');load();}catch{setNotice('Não foi possível alterar o estado. Verifique a sua autorização.');}}
  const action=(table,label)=> <button className="primary" onClick={()=>create(table)} disabled={loading||errors.includes(table)}><Icon name="plus" size={17}/>{label}</button>;
  const tabGroups={finance:manager?[['pagamentos','Pagamentos'],['subscricoes','Subscrições'],['planos_mensalidade','Planos']]:[['subscricoes','Subscrição'],['pagamentos','Pagamentos'],['planos_mensalidade','Planos']],training:[['planos_treino','Planos'],['treinos','Treinos'],['treino_exercicios','Ficha de exercícios'],['exercicios','Biblioteca']],progress:[['registos_treino','Treinos realizados'],['registos_series','Séries'],['medicoes','Medições']]};
  const table=tab||tabGroups[page]?.[0]?.[0];
  const canCreate=page==='finance'?manager:page==='training'?staff:page==='progress';
  function tableRows(t){return rows(t).filter(r=>JSON.stringify({...r,aluno:memberName(r.aluno_id),exercicio:exerciseName(r.exercicio_id),treino:treinoName(r.treino_id)}).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>String(b.criado_em||b.realizado_em||b.medido_em||'').localeCompare(String(a.criado_em||a.realizado_em||a.medido_em||'')));}
  const columns={
    pagamentos:[['Aluno',r=>memberName(r.aluno_id)],['Valor',r=><strong>{money(r.valor,r.moeda)}</strong>],['Método',r=>text(r.metodo)],['Data',r=>date(r.pago_em||r.criado_em)],['Estado',r=><Badge value={r.estado}/>]],
    subscricoes:[['Aluno',r=>memberName(r.aluno_id)],['Plano',r=>rows('planos_mensalidade').find(p=>p.id===r.plano_id)?.nome||'Plano arquivado'],['Preço contratado',r=>money(r.preco_contratado,r.moeda_contratada)],['Período',r=>`${date(r.inicio)} → ${date(r.fim)}`],['Estado',r=><Badge value={r.estado==='ativa'&&r.fim<today()?'expirada':r.estado}/>]],
    planos_mensalidade:[['Plano',r=><strong>{r.nome}</strong>],['Preço',r=>money(r.preco,r.moeda)],['Duração',r=>`${r.duracao_dias} dias`],['Estado',r=><Badge value={r.ativo}/>]],
    planos_treino:[['Plano',r=><strong>{r.nome}</strong>],['Aluno',r=>memberName(r.aluno_id)],['Objetivo',r=>text(r.objetivo)],['Início',r=>date(r.data_inicio)],['Estado',r=><Badge value={r.ativo}/>]],
    treinos:[['Treino',r=><strong>{r.nome}</strong>],['Plano',r=>planName(r.plano_id)],['Ordem',r=>r.ordem]],
    treino_exercicios:[['Treino',r=>treinoName(r.treino_id)],['Exercício',r=><strong>{exerciseName(r.exercicio_id)}</strong>],['Séries × repetições',r=>`${r.series} × ${r.repeticoes}`],['Carga',r=>r.carga_kg==null?'—':`${r.carga_kg} kg`],['Descanso',r=>r.descanso_seg==null?'—':`${r.descanso_seg}s`]],
    exercicios:[['Exercício',r=><strong>{r.nome}</strong>],['Grupo',r=>text(r.grupo_muscular)],['Equipamento',r=>r.equipamento||'—'],['Vídeo',r=>r.video_url?<a href={r.video_url} target="_blank" rel="noreferrer">Ver vídeo ↗</a>:'—'],['Estado',r=><Badge value={r.ativo}/>]],
    registos_treino:[['Aluno',r=>memberName(r.aluno_id)],['Treino',r=>treinoName(r.treino_id)],['Data',r=>date(r.realizado_em)],['Duração',r=>r.duracao_min?`${r.duracao_min} min`:'—'],['Esforço',r=>r.esforco?`${r.esforco}/10`:'—']],
    registos_series:[['Treino',r=>{const reg=rows('registos_treino').find(x=>x.id===r.registo_id);return `${memberName(reg?.aluno_id)} · ${date(reg?.realizado_em)}`;}],['Exercício',r=>exerciseName(r.exercicio_id)],['Série',r=>r.serie],['Repetições',r=>r.repeticoes??'—'],['Carga',r=>r.carga_kg==null?'—':`${r.carga_kg} kg`]],
    medicoes:[['Aluno',r=>memberName(r.aluno_id)],['Data',r=>date(r.medido_em)],['Peso',r=>r.peso_kg?`${r.peso_kg} kg`:'—'],['Gordura',r=>r.gordura_pct?`${r.gordura_pct}%`:'—'],['Altura',r=>r.altura_cm?`${r.altura_cm} cm`:'—']]
  };
  const mayEdit=(t,r)=> t==='pagamentos'?manager&&['pendente','falhado'].includes(r.estado)&&['dinheiro','transferencia','outro'].includes(r.metodo):t==='subscricoes'||t==='planos_mensalidade'?manager:t.startsWith('registos')||t==='medicoes'?true:staff;
  return <div className="workspace">
    <aside className="sidebar"><a className="wordmark" href="#" onClick={e=>{e.preventDefault();navigate('overview');}}><span className="brand-symbol"><Icon name="training" size={26}/></span>fitcore<span className="wordmark-dot">.</span></a>
      <div className="gym-switch"><small>O SEU ESPAÇO</small><select aria-label="Selecionar ginásio" value={gym.id} onChange={e=>onSelectGym(e.target.value)}>{gyms.map(g=><option key={g.id} value={g.id}>{g.nome}</option>)}</select></div>
      <small className="nav-label">GESTÃO DO GINÁSIO</small><nav>{menu.map(([p,label])=><button key={p} className={page===p?'active':''} onClick={()=>navigate(p)} aria-current={page===p?'page':undefined}><Icon name={p}/>{label}{page===p&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-note"><span className="live-dot"/><span>O seu espaço. A sua equipa.<br/><small>Gestão com visão de futuro.</small></span></div>
      <div className="account"><span className="avatar">{initial(membership?.nome)}</span><div><strong>{membership?.nome||'A sua conta'}</strong><small>{text(role)}</small></div><button onClick={onLogout} aria-label="Sair da conta"<button
  type="button"
  onClick={onLogout}
  aria-label="Sair da conta"
>
  Terminar sessão
</button>
    </aside>
    <div className="workspace-body"><header className="topbar"><span>O seu espaço <b>/</b> {menu.find(x=>x[0]===page)?.[1]}</span><div><span className="topbar-status"><i/> {gym.nome}</span><span className="avatar small">{initial(membership?.nome)}</span><button className="icon-button mobile-logout" onClick={onLogout} aria-label="Sair da conta"><Icon name="exit" size={18}/></button></div></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow">FITCORE / {text(role).toUpperCase()}</div><h1>{headings[page][0]}</h1><p>{headings[page][1]}</p></div><button className="icon-button" onClick={load} disabled={loading} aria-label="Atualizar dados"><Icon name="refresh"/></button></div>
      {authError&&<div className="alert" role="alert">{authError}</div>}
      {errors.length>0&&<div className="alert" role="alert">Alguns dados não puderam ser carregados ({errors.join(', ')}). Atualize para tentar novamente. Os indicadores podem estar incompletos.</div>}
      {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Fechar aviso"><Icon name="close" size={16}/></button></div>}
      {loading?<div className="loading-state" role="status"><span className="spinner"/>A preparar o seu espaço…</div>:page==='overview'?<>
        <section className="welcome"><div className="welcome-content"><span className="welcome-label"><span className="live-dot"/> {gym.nome}</span><h2>Mais foco nas pessoas.<br/><em>Mais visão no negócio.</em></h2><p>Bem-vindo, {membership?.nome?.split(' ')[0]||'gestor'}. Um novo dia para transformar objetivos em resultados.</p><button className="primary" onClick={()=>navigate(staff?'members':'training')}>{staff?'Conhecer os membros':'Ver os meus treinos'}<Icon name="arrow" size={18}/></button></div><div className="welcome-art" aria-hidden="true"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="art-core"><Icon name="training" size={70}/></div><span className="art-caption">FORÇA. FOCO. EVOLUÇÃO.</span></div></section>
        <section className="metrics"><Metric label={staff?'Alunos ativos':'Os meus treinos'} value={staff?alumnos.length:myRecords.length} detail={staff?'Com vínculo ativo no ginásio':'Treinos registados'} icon="members"/>
          {role!=='trainer'?<Metric label={manager?'Recebido este mês':'Pago este mês'} value={financeTotal(paid)} detail="Pagamentos confirmados, sem reembolsos" icon="finance"/>:<Metric label="Biblioteca de exercícios" value={rows('exercicios').filter(x=>x.ativo).length} detail="Exercícios ativos" icon="training"/>}
          <Metric label={role==='trainer'?'Planos de treino':'Subscrições em vigor'} value={role==='trainer'?rows('planos_treino').filter(p=>p.ativo).length:activeSubs.length} detail="Registos ativos" icon="check"/><Metric label="Treinos realizados" value={rows('registos_treino').length} detail={staff?'Todos os registos do ginásio':'O seu histórico'} icon="progress"/></section>
        <div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">{role==='trainer'?'EVOLUÇÃO':'FINANCEIRO'}</span><h2>{role==='trainer'?'Atividade de treino':'Recebimentos em AOA'}</h2></div><span className="soft-label">Últimos 6 meses</span></div><MonthChart items={role==='trainer'?rows('registos_treino'):payments.filter(p=>p.estado==='pago'&&p.moeda==='AOA')} training={role==='trainer'}/></section>
          <section className="panel"><div className="panel-heading"><div><span className="eyebrow">A SUA COMUNIDADE</span><h2>{staff?'Equipa & membros':'A sua conta'}</h2></div><button className="text-button" onClick={()=>navigate('members')}>Ver todos ↗</button></div>{members.length?members.slice(0,4).map(m=><div className="member-line" key={m.utilizador_id}><span className="avatar">{initial(m.nome)}</span><div><strong>{m.nome}</strong><small>{text(m.funcao)}</small></div><Badge value={m.ativo}/></div>):<Empty title="O primeiro capítulo começa aqui" detail="Os membros associados ao ginásio aparecerão aqui."/>}</section></div>
        <section className="quick-actions">{[['training','Planear o próximo treino','Transforme objetivos em planos.'],['progress','Acompanhar a evolução','Cada progresso merece um registo.'],[role==='trainer'?'members':'finance',role==='trainer'?'Conhecer os alunos':'Organizar as mensalidades',role==='trainer'?'A equipa certa para cada objetivo.':'Uma relação financeira mais clara.']].map(([p,title,detail])=><button key={p} onClick={()=>navigate(p)}><span className="quick-icon"><Icon name={p}/></span><span><strong>{title}</strong><small>{detail}</small></span><Icon name="arrow" size={18}/></button>)}</section>
      </>:page==='members'?<section className="panel"><div className="panel-heading"><div><h2>{staff?'Membros do ginásio':'O seu vínculo'}</h2><p>{members.length} {members.length===1?'pessoa':'pessoas'} · {members.filter(m=>m.ativo).length} ativas</p></div></div><Search value={query} onChange={setQuery}/><div className="member-grid">{members.filter(m=>`${m.nome} ${m.funcao}`.toLowerCase().includes(query.toLowerCase())).map(m=><article className="member-card" key={m.utilizador_id}><span className="avatar large">{initial(m.nome)}</span><Badge value={m.ativo}/><h3>{m.nome}</h3><p>{text(m.funcao)}</p><span className="member-caption">{gym.nome}</span></article>)}</div>{!members.length&&<Empty title="Sem membros disponíveis"/>}<p className="panel-footnote">A criação de contas e a atribuição de acessos são feitas pelo administrador da plataforma.</p></section>
      :page==='settings'?<Settings gym={gym} user={user} manager={manager} onSaved={onSaved}/>
      :<><div className="tabs" role="tablist">{tabGroups[page].map(([t,label])=><button role="tab" aria-selected={table===t} key={t} className={table===t?'selected':''} onClick={()=>{setTab(t);setQuery('');}}>{label}<span>{rows(t).length}</span></button>)}</div>
        <section className="panel"><div className="panel-heading"><div><h2>{tabGroups[page].find(([t])=>t===table)?.[1]}</h2><p>{rows(table).length} registos no seu espaço</p></div>{canCreate&&action(table,table==='treino_exercicios'?'Adicionar exercício':table==='registos_series'?'Registar série':table==='pagamentos'?'Registar pagamento':'Novo registo')}</div>
        {table==='pagamentos'&&manager&&<p className="panel-footnote">Registe aqui pagamentos manuais. Pagamentos online e reembolsos são confirmados pelo serviço administrativo.</p>}
        {table==='medicoes'&&<MeasurementChart items={rows(table)} members={members} user={user} staff={staff}/>}
        <Search value={query} onChange={setQuery}/>
        {errors.includes(table)?<Empty title="Não foi possível carregar esta secção" detail="Verifique a ligação e tente atualizar os dados."/>:tableRows(table).length?<div className="table-scroll"><table><thead><tr>{columns[table].map(([title])=><th key={title}>{title}</th>)}<th><span className="sr-only">Ações</span></th></tr></thead><tbody>{tableRows(table).map(r=><tr key={r.id}>{columns[table].map(([title,render])=><td key={title}>{render(r)}</td>)}<td><div className="row-actions">{mayEdit(table,r)&&<button onClick={()=>edit(table,r)}>Editar</button>}{staff&&['exercicios','planos_treino'].includes(table)||manager&&table==='planos_mensalidade'?<button onClick={()=>toggle(table,r)}>{r.ativo?'Arquivar':'Ativar'}</button>:null}</div></td></tr>)}</tbody></table></div>:<Empty title={query?'Nenhum resultado encontrado':'Um espaço pronto para começar'} detail={query?'Experimente outro nome ou termo de pesquisa.':'Ainda não há registos nesta secção.'}/>}
        </section></>}
      <footer className="workspace-footer"><span>fitcore<span>.</span> <small>Gestão que acompanha a sua ambição.</small></span><small>{gym.nome} · {text(role)}</small></footer>
      </div></div>
      {modal&&<RecordForm modal={modal} gymId={gym.id} onClose={()=>setModal(null)} onSuccess={()=>{setModal(null);setNotice('Registo guardado com sucesso.');load();}}/>}
    </div>;
}

function Search({value,onChange}) {return <label className="search"><Icon name="search" size={18}/><input type="search" value={value} onChange={e=>onChange(e.target.value)} placeholder="Pesquisar registos…" aria-label="Pesquisar registos"/></label>;}
function MonthChart({items,training}) {const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return {label:d.toLocaleDateString('pt-AO',{month:'short'}),value:items.filter(p=>(training?p.realizado_em:p.pago_em)?.startsWith(key)).reduce((sum,p)=>sum+(training?1:Number(p.valor)),0)};});const max=Math.max(...months.map(m=>m.value),1);return <div className="bar-chart" role="img" aria-label={months.map(m=>`${m.label}: ${training?m.value:money(m.value)}`).join('; ')}>{months.map((m,i)=><div className="bar-column" key={i}><span>{training?m.value:money(m.value)}</span><div className="bar-track"><div className={i===5?'current':''} style={{height:`${Math.max(m.value/max*100,m.value?3:0)}%`}}/></div><small>{m.label}</small></div>)}</div>;}
function MeasurementChart({items,members,user,staff}) {const [person,setPerson]=useState(user.id);const available=[...new Set(items.map(m=>m.aluno_id))];const chosen=available.includes(person)?person:available[0];const records=items.filter(m=>m.aluno_id===chosen&&m.peso_kg!=null).sort((a,b)=>a.medido_em.localeCompare(b.medido_em));if(!records.length)return null;const values=records.map(m=>Number(m.peso_kg)),min=Math.min(...values)-1,max=Math.max(...values)+1;const points=records.map((r,i)=>`${30+i*540/Math.max(records.length-1,1)},${125-(Number(r.peso_kg)-min)/(max-min)*95}`).join(' ');return <div className="weight-chart">{staff&&<select aria-label="Aluno do gráfico" value={chosen} onChange={e=>setPerson(e.target.value)}>{available.map(id=><option key={id} value={id}>{members.find(m=>m.utilizador_id===id)?.nome||'Aluno'}</option>)}</select>}<div className="panel-heading"><strong>Evolução do peso</strong><span>{values.at(-1)} kg · última medição</span></div><svg viewBox="0 0 600 160" role="img" aria-label={records.map(r=>`${date(r.medido_em)}: ${r.peso_kg} kg`).join('; ')}><path d="M30 30H570 M30 75H570 M30 125H570" stroke="#273135"/><polyline points={points} fill="none" stroke="#d9b773" strokeWidth="3"/>{points.split(' ').map((p,i)=><circle key={i} cx={p.split(',')[0]} cy={p.split(',')[1]} r="4" fill="#d9b773"/>)}</svg><small>{date(records[0].medido_em)} — {date(records.at(-1).medido_em)}</small></div>;}

function RecordForm({modal,gymId,onClose,onSuccess}) {
  const ref=useRef(null);const previous=useRef(document.activeElement);
  const [values,setValues]=useState(()=>Object.fromEntries(modal.fields.map(f=>[f.key,f.fixed??modal.defaults?.[f.key]??f.default??''])));
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector('input,select,textarea,button')?.focus();return()=>{document.body.style.overflow=old;previous.current?.focus();};},[]);
  function change(key,value){setValues(v=>{const next={...v,[key]:value};modal.fields.filter(f=>f.depends===key).forEach(f=>{next[f.key]='';});return next;});}
  async function save(e){e.preventDefault();setError('');if(values.fim&&values.inicio&&values.fim<values.inicio){setError('A data de fim deve ser igual ou posterior ao início.');return;}if(modal.table==='medicoes'&&!modal.fields.some(f=>f.type==='number'&&values[f.key]!=='')){setError('Introduza pelo menos uma medição.');return;}setBusy(true);try{const payload={};for(const f of modal.fields){const value=values[f.key];payload[f.key]=value===''?null:f.type==='number'?Number(value):f.type==='datetime-local'?new Date(value).toISOString():typeof value==='string'?value.trim():value;}if(!modal.id)payload.ginasio_id=gymId;if(modal.table==='pagamentos'){payload.pago_em=payload.estado==='pago'?new Date().toISOString():null;const sub=modal.fields.find(f=>f.key==='subscricao_id')?.source?.find(s=>s.id===payload.subscricao_id);if(sub&&sub.moeda_contratada!==payload.moeda){setError('A moeda do pagamento deve corresponder à moeda contratada na subscrição.');setBusy(false);return;}}let request=modal.id?supabase.from(modal.table).update(payload).eq('id',modal.id).eq('ginasio_id',gymId):supabase.from(modal.table).insert(payload);const {data,error}=await request.select('id');if(error||!data?.length)throw error||Error('Sem autorização');onSuccess();}catch(err){setError(err?.code==='23505'?'Já existe um registo com estes dados.':err?.code==='23503'?'O registo associado não está disponível. Atualize e tente novamente.':err?.code==='42501'?'A sua conta não tem autorização para esta operação.':err?.code==='23514'?'Verifique os valores: um campo não cumpre as regras de validação.':err?.code==='P0001'?err.message:'Não foi possível guardar. Verifique a ligação e tente novamente.');}finally{setBusy(false);}}
  function trap(e){if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input,select,textarea')];if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
  return <div className="modal-backdrop"><section ref={ref} className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onKeyDown={trap}><div className="modal-heading"><div><span className="eyebrow">O SEU GINÁSIO / NOVO CAPÍTULO</span><h2 id="modal-title">{modal.title}</h2></div><button className="icon-button" disabled={busy} onClick={onClose} aria-label="Fechar formulário"><Icon name="close"/></button></div><form onSubmit={save}><div className="form-grid">{modal.fields.filter(f=>f.fixed===undefined).map(f=>{let options=f.options||[];if(f.depends){const allowed=new Set((f.source||[]).filter(x=>f.filter(x,values[f.depends])).map(x=>x.id));options=options.filter(x=>allowed.has(x.value));}const props={value:values[f.key],onChange:e=>change(f.key,e.target.value),required:f.required,id:'field-'+f.key};return <label key={f.key} className={f.type==='textarea'?'full':''}>{f.label}{f.required&&<span className="required"> *</span>}{f.type==='select'?<select {...props}><option value="">{f.required?'Selecionar…':'Sem associação'}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea {...props} maxLength={f.maxLength} rows="3"/>:<input {...props} type={f.type} min={f.min} max={f.max} step={f.step} pattern={f.pattern} maxLength={f.maxLength}/>} {f.hint&&<small>{f.hint}</small>}{f.required&&f.type==='select'&&!options.length&&<small>Não há opções disponíveis. Crie primeiro o registo associado.</small>}</label>;})}</div>{error&&<p className="alert" role="alert">{error}</p>}<div className="modal-actions"><button type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'A guardar…':'Guardar registo'}<Icon name="check" size={17}/></button></div></form></section></div>;
}

function Settings({gym,manager,onSaved}) {const [name,setName]=useState(gym.nome),[logo,setLogo]=useState(gym.logo_url||''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');async function save(e){e.preventDefault();setBusy(true);setMessage('');try{const {data,error}=await supabase.from('ginasios').update({nome:name.trim(),logo_url:logo.trim()||null}).eq('id',gym.id).select('id,nome,slug,logo_url').single();if(error)throw error;onSaved(data);setMessage('A identidade do ginásio foi atualizada.');}catch{setMessage('Não foi possível guardar. Verifique os campos e a sua autorização.');}finally{setBusy(false);}}return <div className="settings-layout"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">IDENTIDADE</span><h2>Uma marca com personalidade.</h2><p>O nome apresentado a toda a sua comunidade.</p></div></div><form onSubmit={save}><label>Nome do ginásio<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120} disabled={!manager}/></label><label>Endereço HTTPS do logótipo<input type="url" pattern="https://.*" value={logo} onChange={e=>setLogo(e.target.value)} maxLength={500} placeholder="https://…" disabled={!manager}/></label>{manager&&<button className="primary" disabled={busy}>{busy?'A guardar…':'Guardar alterações'}<Icon name="check" size={17}/></button>}{message&&<p role="status">{message}</p>}</form></section><section className="brand-preview"><span className="eyebrow">A SUA MARCA</span>{logo?<img src={logo} alt="Pré-visualização do logótipo" referrerPolicy="no-referrer"/>:<span className="preview-monogram">{initial(name)}</span>}<h2>{name||'O seu ginásio'}</h2><p>Uma comunidade.<br/>Uma ambição partilhada.</p><span className="soft-label">powered by fitcore.</span></section></div>;}
